---

N_PROCS: 4
N_GEN: 1000000

DX: 0.1
DT: 0.01
WIDTH: 128
HEIGHT: 128
THR: 0.5
NUM_INIT_PTS: 25
N_ITERS: 500000
RTOL_EARLY_STOP: 1e-5

POP_SIZE: 16
EVAL_INIT_FITNESS: True
INIT_POP: "../population/init_pop_axyridis" 
INITIALIZER: "liaw"
OBJECTIVES:
  - ["MeanMeanSquareError", 1e-1, "cpu"]
  - ["MeanColorProportion", 1e0, "cpu"]
  - ["MeanVgg16PerceptualLoss", 1e-4, "cuda"]
  - ["MeanLearnedPerceptualImagePatchSimilarity:vgg", 1.5e1, "cuda"]
  - ["MeanLearnedPerceptualImagePatchSimilarity:alex", 4e0, "cuda"]
LADYBIRD_TYPE: "haxyridis"
LADYBIRD_SUBTYPES: ["axyridis"]
DPATH_OUTPUT: "./output"
