---
   
DX: 0.1
DT: 0.01
WIDTH: 128
HEIGHT: 128
THR: 0.5
N_ITERS: 500000
    
POP_SIZE: 20
INIT_POP: "initpop.json"
INITIALIZER: "liaw"

OBJECTIVE: "MinMeanSquareError"
OBJECTIVE_DEVICE: "cpu"

LADYBIRD_TYPE: "haxyridis"
LADYBIRD_SUBTYPES: ["axyridis"] #, "succinea", "spectabilis", "conspicua"]
DPATH_OUTPUT: "../output"
