---

DEVICE: "cuda:0"

VERBOSE: 1
PERIOD_OUTPUT: 10000

BATCH_SIZE: 64
DPATH_DATASET:
DPATH_AUGDATASET:

DX: 0.1
DT: 0.01
WIDTH: 128
HEIGHT: 128
THR: 0.5
NUM_INIT_PTS: 25
N_ITERS: 500
RTOL_EARLY_STOP: 1e-5

