---

DEVICE: "cuda:0"

VERBOSE: 1

N_EPOCHS: 10000
BATCH_SIZE: 64
DPATH_INPUT_DATASET: ...
DPATH_OUTPUT_DATASET: ...

INITIALIZER: "Liaw"
MODEL: "Liaw"
SOLVER: "Euler"

DX: 0.1
DT: 0.01
WIDTH: 128
HEIGHT: 128
THR_COLOR: 0.5
N_INIT_PTS: 25
N_ITERS: 500000
