---

#DEVICE: "cuda:0"

VERBOSE: 1

BATCH_SIZE: 64
DPATH_DATASET: "/data/lpf/dataset_axyridis"
DPATH_AUGDATASET: "/home/dwlee/repos/lpf/augmentation/output"

INITIALIZER: "Liaw"
MODEL: "Liaw"
SOLVER: "Euler"

DX: 0.1
DT: 0.01
WIDTH: 128
HEIGHT: 128
THR_COLOR: 0.5
N_INIT_PTS: 25
N_ITERS: 500000
RTOL_EARLY_STOP: 1e-5

