---

DEVICE: "cuda:1"

N_AUGMENTATION: 10
BATCH_SIZE: 64

VERBOSE: 1
PERIOD_OUTPUT: 4999999

DPATH_DATASET: /data/lpf/dataset_succinea
DPATH_AUGDATASET: /data/lpf/augdataset_succinea

DX: 0.1
DT: 0.01
WIDTH: 128
HEIGHT: 128
THR: 0.5
NUM_INIT_PTS: 25
N_ITERS: 500000
RTOL_EARLY_STOP: 1e-5

